[package]
name = "parser2"
version = "0.1.0"
authors = ["sunakan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemallocator = "0.3.2"
nom = "6.0.1"
